
hs.loadSpoon("ModalMgr")
hs.loadSpoon("ClipShow")
require 'configs.shortcuts'

if spoon.ClipShow then
    spoon.ModalMgr:new("clipshowM")
    local cmodal = spoon.ModalMgr.modal_list["clipshowM"]
    cmodal:bind('', 'escape', '退出 剪切板', function()
        spoon.ClipShow:toggleShow()
        spoon.ModalMgr:deactivate({"clipshowM"})
    end)
    cmodal:bind('', 'Q', '退出 剪切板', function()
        spoon.ClipShow:toggleShow()
        spoon.ModalMgr:deactivate({"clipshowM"})
    end)
    cmodal:bind('', 'Return', 'Enter键粘贴', function()
        hs.eventtap.keyStroke({ "cmd" }, "v")
        spoon.ClipShow:toggleShow()
        spoon.ModalMgr:deactivate({"clipshowM"})
    end)
    cmodal:bind('', 'S', '保存此会话', function()
        spoon.ClipShow:saveToSession()
    end)
    cmodal:bind('', 'R', '恢复上一个会话', function()
        spoon.ClipShow:restoreLastSession()
    end)
    cmodal:bind('', 'g', 'Google 打开/搜索', function()
        spoon.ClipShow:openInBrowserWithRef()
        spoon.ClipShow:toggleShow()
        spoon.ModalMgr:deactivate({"clipshowM"})
    end)
    cmodal:bind('', 'H', '在 Github 中搜索', function()
        spoon.ClipShow:openInBrowserWithRef("https://github.com/search?q=")
        spoon.ClipShow:toggleShow()
        spoon.ModalMgr:deactivate({"clipshowM"})
    end)
    cmodal:bind('', 'D', '保存到桌面', function()
        spoon.ClipShow:saveToFile()
        -- spoon.ClipShow:saveToFile("~/Downloads/")
        spoon.ClipShow:toggleShow()
        spoon.ModalMgr:deactivate({"clipshowM"})
    end)
    cmodal:bind('', 'N', '用 neovide 打开', function()
        spoon.ClipShow:openWithCommand("/usr/local/bin/nvide")
        spoon.ClipShow:toggleShow()
        spoon.ModalMgr:deactivate({"clipshowM"})
    end)
    cmodal:bind('', 'V', '用 VSCode 打开', function()
        spoon.ClipShow:openWithCommand("/usr/local/bin/vscode")
        spoon.ClipShow:toggleShow()
        spoon.ModalMgr:deactivate({"clipshowM"})
    end)
    cmodal:bind('', 'B', 'Base64 解码', function()
        spoon.ClipShow:base64EncodeOrDecode("decode")
    end)
    cmodal:bind({"Shift"}, 'B', 'Base64 编码', function()
        spoon.ClipShow:base64EncodeOrDecode("encode")
    end)
    cmodal:bind("", 'U', 'URL 解码', function()
        spoon.ClipShow:urlEncodeOrDecode("decode")
    end)
    cmodal:bind({"Shift"}, 'U', 'URL 编码', function()
        spoon.ClipShow:urlEncodeOrDecode("encode")
    end)
    cmodal:bind('', 'M', 'MD5 值', function()
        spoon.ClipShow:md5sum()
    end)
    cmodal:bind({"Shift"}, 'M', 'Markdown转 HTML', function()
        spoon.ClipShow:markdownToHtml()
    end)
    cmodal:bind('', 'T', '去多余空格换行', function()
        spoon.ClipShow:trimSpace()
    end)

    -- 绑定功 clipshowM 快捷键
    local hsclipsM_keys = clipBoardTools or {"alt", "C"}
    if string.len(hsclipsM_keys[2]) > 0 then
        spoon.ModalMgr.supervisor:bind(hsclipsM_keys[1], hsclipsM_keys[2], "打开剪切板面板", function()
            spoon.ClipShow:toggleShow()
            if spoon.ClipShow.canvas:isShowing() then
                spoon.ModalMgr:deactivateAll()
                spoon.ModalMgr:activate({"clipshowM"})
            end
        end)
    end
end