---@diagnostic disable: lowercase-global

-- require "configs.windowConfig"

winman_keys = {
    { -- quit
        prefix = {},
        key = "Q",
        message = "Quit WinMan",
        tag = 'origin'
    },
    { -- 左半屏
        prefix = {},
        -- key = "Left",
        key = "H",
        message = "Left Half",
        func = "moveAndResize",
        location = "halfleft",
        tag = "origin",
    },
    { -- 右半屏
        prefix = {},
        key = "L",
        message = "Right Half",
        func = "moveAndResize",
        location = "halfright",
        tag = "origin",
    },
    { -- 上半屏
        prefix = {},
        key = "K",
        message = "Up Half",
        func = "moveAndResize",
        location = "halfup",
        tag = "origin",
    },
    { -- 下半屏
        prefix = {},
        key = "J",
        message = "Down Half",
        func = "moveAndResize",
        location = "halfdown",
        tag = "origin",
    },
    -- 窗口平移至当前屏幕四个角落, 不会改变窗口原来尺寸
    {
        prefix = {},
        key = "Y",
        message = "窗口移到屏幕左上角 ↖️ ",
        func = "moveAndResize",
        location = "screenCornerNW",
        tag = "origin",
    },
    {
        prefix = {},
        key = "U",
        message = "窗口移到屏幕右上角 ↗️ ",
        func = "moveAndResize",
        location = "screenCornerNE",
        tag = "origin",
    },
    {
        prefix = {},
        key = "I",
        message = "窗口移到屏幕左下角 ↙️ ",
        func = "moveAndResize",
        location = "screenCornerSW",
        tag = "origin",
    },
    {
        prefix = {},
        key = "O",
        message = "窗口移到屏幕右下角 ↘️ ",
        func = "moveAndResize",
        location = "screenCornerSE",
        tag = "origin",
    },
    {
        prefix = {},
        key = "P",
        message = "开关全屏",
        func = "moveAndResize",
        location = "fullscreen",
        tag = "origin",
    },
    {
        prefix = {'Ctrl'},
        key = "M",
        message = "最大化",
        func = "moveAndResize",
        location = "max",
        tag = "origin",
    },
    {
        prefix = {},
        key = "C",
        message = "窗口移到屏幕正中",
        func = "moveAndResize",
        location = "center",
        tag = "origin",
    },
    {
        prefix = {},
        key = "Z",
        message = "撤销上次窗口操作",
        func = "undo",
        location = "",
        tag = "origin",
    },
    {
        prefix = {'Ctrl'},
        key = "R",
        message = "恢复上次窗口操作",
        func = "undo",
        location = "",
        tag = "origin",
    },
    -- 窗口平移至当前屏幕左右顶底四边, 不会改变窗口原来尺寸
    {
        prefix = { "Ctrl", "Shift" },
        key = "H",
        message = "窗口移到屏幕左边",
        func = "moveAndResize",
        location = "screenLB",
        tag = "origin",
    },
    {
        prefix = { "Ctrl", "Shift" },
        key = "J",
        message = "窗口移到屏幕底边",
        func = "moveAndResize",
        location = "screenDB",
        tag = "origin",
    },
    {
        prefix = { "Ctrl", "Shift" },
        key = "K",
        message = "窗口移到屏幕顶边",
        func = "moveAndResize",
        location = "screenUB",
        tag = "origin",
    },
    {
        prefix = { "Ctrl", "Shift" },
        key = "L",
        message = "窗口移到屏幕右边",
        func = "moveAndResize",
        location = "screenRB",
        tag = "origin",
    },
    -- 改变原来窗口尺寸至 1/4 屏幕大小
    {
        prefix = { "Ctrl", "Shift" },
        key = "Y",
        message = "屏幕左上角 ↖️ ",
        func = "moveAndResize",
        location = "cornerNW",
        tag = "origin",
    },
    {
        prefix = { "Ctrl", "Shift" },
        key = "U",
        message = "屏幕右上角 ↗️ ",
        func = "moveAndResize",
        location = "cornerNE",
        tag = "origin",
    },
    {
        prefix = { "Ctrl", "Shift" },
        key = "I",
        message = "屏幕左下角 ↙️ ",
        func = "moveAndResize",
        location = "cornerSW",
        tag = "origin",
    },
    {
        prefix = { "Ctrl", "Shift" },
        key = "O",
        message = "屏幕右下角 ↘️ ",
        func = "moveAndResize",
        location = "cornerSE",
        tag = "origin",
    },
    {
        prefix = { "Ctrl", "Shift" },
        key = "E",
        message = "窗口拉伸",
        func = "moveAndResize",
        location = "expand",
        tag = "origin",
    },
    {
        prefix = { "Ctrl", "Shift" },
        key = "S",
        message = "窗口收缩",
        func = "moveAndResize",
        location = "shrink",
        tag = "origin",
    },
    {
        prefix = {},
        key = "left",
        message = "窗口向左收缩 ⬅️ ",
        func = "stepResize",
        direction = "left",
        tag = "origin",
    },
    {
        prefix = {},
        key = "right",
        message = "窗口向右扩展 ➡️ ",
        func = "stepResize",
        direction = "right",
        tag = "origin",
    },
    {
        prefix = { "Ctrl" },
        key = "right",
        message = "窗口向右扩展 ➡️ ",
        func = "stepResize",
        direction = "rightExpanToScreen",
        tag = "origin",
    },
    {
        prefix = { "Ctrl" },
        key = "left",
        message = "窗口向左扩展 ⬅️ ",
        func = "stepResize",
        direction = "leftExpanToScreen",
        tag = "origin",
    },
    {
        prefix = { "Ctrl" },
        key = "up",
        message = "窗口向上扩展 ⬆️ ",
        func = "stepResize",
        direction = "upExpanToScreen",
        tag = "origin",
    },
    {
        prefix = { "Ctrl" },
        key = "down",
        message = "窗口向下扩展 ⬇️ ",
        func = "stepResize",
        direction = "downExpanToScreen",
        tag = "origin",
    },
    {
        prefix = {},
        key = "up",
        message = "窗口向上收缩 ⬆️ ",
        func = "stepResize",
        direction = "up",
        tag = "origin",
    },
    {
        prefix = {},
        key = "down",
        message = "窗口向下扩展 ⬇️ ",
        func = "stepResize",
        direction = "down",
        tag = "origin",
    },
    {
        prefix = {},
        key = "A",
        message = "窗口移至左边屏幕",
        func = "wMoveToScreen",
        location = "left",
        tag = "origin",
    },
    -- {
    --     prefix = {},
    --     key = "T",
    --     message = "窗口移至上边屏幕",
    --     func = "wMoveToScreen",
    --     location = "up",
    --     tag = "origin",
    -- },
    -- {
    --     prefix = {},
    --     key = "B",
    --     message = "窗口移动下边屏幕",
    --     func = "wMoveToScreen",
    --     location = "down",
    --     tag = "origin",
    -- },
    {
        prefix = {},
        key = "N",
        message = "窗口移至右边屏幕",
        func = "wMoveToScreen",
        location = "right",
        tag = "origin",
    },
    {
        prefix = {},
        -- key = "S",
        key = "B",
        message = "窗口移至上一个Space",
        func = "moveToSpace",
        direction = "left",
        -- 是否跟随窗口一起跳到新空间并聚焦
        followWindow = true,
        tag = "origin",
    },
    {
        prefix = {},
        key = "D",
        message = "窗口移至下一个Space",
        func = "moveToSpace",
        direction = "right",
        -- 'false' : 不会跟随窗口移动, 并会在当前 space 自动点击最上层的窗口以获取焦点
        followWindow = false,
        tag = "origin",
    },
    -- 对同一 APP 所有窗口
    {
        prefix = { "Ctrl", "Shift" },
        key = "F",
        message = "同一APP所有窗口平铺",
        func = "flattenWindow",
        location = "",
        tag = "origin",
    },
    {
        prefix = { "Ctrl", "Shift" },
        key = "G",
        message = "同一APP所有窗口网格",
        func = "gridWindow",
        location = "",
        tag = "origin",
    },
    {
        prefix = { "Ctrl", "Shift" },
        key = "R",
        message = "切换同一APP窗口布局 🔄",
        func = "rotateLayout",
        location = "",
        tag = "origin",
    },
    -- 对同一 Space 所有APP所有窗口
    {
        prefix = {},
        key = "F",
        message = "所有窗口平铺",
        func = "flattenWindowsForSpace",
        location = "",
        tag = "origin",
    },
    {
        prefix = {},
        key = "G",
        message = "所有窗口网格",
        func = "gridWindowsForSpace",
        location = "",
        tag = "origin",
    },
    {
        prefix = {},
        key = "R",
        message = "切换所有窗口布局 🔄",
        func = "rotateLayoutWindowsForSpace",
        location = "",
        tag = "origin",
    },
    {
        prefix = {},
        key = "X",
        message = "killSameAppAllWindow",
        func = "killSameAppAllWindow",
        location = "",
        tag = "origin",
    },
    {
        prefix = {},
        key = "V",
        -- message = "closeSameAppOtherWindows",
        message = "关闭同应用其他窗口",
        func = "closeSameAppOtherWindows",
        location = "",
        tag = "origin",
    },

    ------ Grid 模式键绑定配置 ------
    {
        prefix = {},
        key = "H",
        message = "窗口在屏幕左半部布局组",
        mapGridGroup = window_grid_groups.LeftGrid,
        tag = "grid",
    },
    {
        prefix = {},
        key = "L",
        message = "窗口在屏幕右半部布局组",
        mapGridGroup = window_grid_groups.RightGrid,
        tag = "grid",
    },
    {
        prefix = {},
        key = "K",
        message = "窗口在屏幕顶部布局组",
        mapGridGroup = window_grid_groups.TopGrid,
        tag = "grid",
    },
    {
        prefix = {},
        key = "J",
        message = "窗口在屏幕底部布局组",
        mapGridGroup = window_grid_groups.BottomGrid,
        tag = "grid",
    },
    {
        prefix = {},
        key = "S",
        message = "窗口在屏幕四角布局组",
        mapGridGroup = window_grid_groups.cornerGrid,
        tag = "grid",
    },
    {
        prefix = {},
        key = "C",
        message = "窗口在屏幕中心部布局组",
        mapGridGroup = window_grid_groups.CenterGrid,
        tag = "grid",
    },
    {
        prefix = {},
        key = "F",
        message = "窗口在屏幕四边半屏布局组",
        mapGridGroup = window_grid_groups.HalfScreenGrid,
        tag = "grid",
    },
    {
        prefix = {},
        key = "Z",
        message = "Undo",
        mapGridGroup = 'Undo',
        tag = "grid",
    },
    {
        prefix = {},
        key = "R",
        message = "Redo",
        mapGridGroup = 'Redo',
        tag = "grid",
    },
    {
        prefix = {},
        key = "T",
        message = "switchToTileMode",
        mapGridGroup = 'switchToTileMode',
        tag = "grid",
    },

    ------ Tile 模式键绑定配置 ------
    {
        prefix = {},
        key = "T",
        -- 优先水平方向均分模式
        message = "tallMode",
        mode = 'tall',
        tag = "tile",
    },
    {
        prefix = {},
        key = "M",
        -- -- 双栏模式
        message = "tallTwoMode",
        mode = 'talltwo',
        tag = "tile",
    },
    {
        prefix = {},
        key = ",",
        -- -- 优先垂直方向均分模式
        message = "wideMode",
        mode = 'wide',
        tag = "tile",
    },
    {
        prefix = {},
        key = ";",
        -- -- 全屏(最大化)模式
        message = "fullScreenMode",
        mode = 'fullscreen',
        tag = "tile",
    },
    {
        prefix = { "Ctrl" },
        key = "J",
        -- 聚焦下一个窗口
        message = "focusNext",
        action = "focus",
        direction = 'next',
        tag = "tile",
    },
    {
        prefix = { "Ctrl" },
        key = "K",
        -- -- 聚焦上一个窗口
        message = "focusPrev",
        action = "focus",
        direction = 'prev',
        tag = "tile",
    },
    {
        prefix = { "Ctrl" },
        key = "L",
        -- -- 与下一个窗口交互位置
        message = "swapNext",
        action = "swap",
        direction = 'next',
        tag = "tile",
    },
    {
        prefix = { "Ctrl" },
        key = "H",
        -- -- 与上一个窗口交互位置
        message = "swapPrev",
        action = "swap",
        direction = 'prev',
        tag = "tile",
    },
    {
        prefix = { "Ctrl" },
        key = "I",
        -- 与第一个窗口交互位置
        message = "swapFirst",
        action = "swap",
        direction = 'first',
        tag = "tile",
    },
    {
        prefix = {},
        key = "E",
        -- 布局分割线右移伸展
        message = "incMainRatio",
        action = "resizeWidth",
        sizeVal = 0.05,
        tag = "tile",
    },
    {
        -- prefix = { "Ctrl" },
        prefix = {},
        key = "S",
        -- -- 布局分割线左移收缩
        message = "decMainRatio",
        action = "resizeWidth",
        sizeVal = -0.05,
        tag = "tile",
    },
    {
        prefix = { "Ctrl" },
        key = "S",
        -- -- 当前聚焦窗口高度折半
        message = "decMainWindows",
        action = "resizeHeight",
        sizeVal = 1,
        tag = "tile",
    },
    {
        prefix = { "Ctrl" },
        key = "E",
        -- -- 当前聚焦窗口高度增倍
        message = "incMainWindows",
        action = "resizeHeight",
        sizeVal = -1,
        tag = "tile",
    },
    {
        prefix = { "Ctrl" },
        key = "D",
        -- 优先水平方向均分模式
        message = "fullScreenMode",
        action = "showMode",
        tag = "tile",
    },
}